Добавил билеты по матану и алгебре
platonlukyanov/exams pull request #11
Opened 2024-10-28 09:12 UTC by klopov-aleksei

2024-10-28 16:04 UTC, PanVOUniversity requested changes
Посмотри иерархию в репозитории и поменяй иерархию папок. Нам будет тяжело мерджить потом

2024-10-28 17:10 UTC, klopov-aleksei commented
> Посмотри иерархию в репозитории и поменяй иерархию папок. Нам будет тяжело мерджить потом

Не понимаю, что ты понимаешь под иерархией папок. Я добавил images (и это удобно, я считаю) и внутри папки analysis и algebra подпапка для коллоквиума. Структуры как таковой ещё нет, но мне кажется, если мы собираемся этот гитхаб не закрывать после коллоков, то создание подобных подпапок пойдёт на пользу.

2024-10-29 19:48 UTC, PanVOUniversity commented
Согл, тупанули, не договорились с иерархией заранее. Билеты норм

2024-10-29 19:49 UTC, PanVOUniversity approved these changes

2024-10-30 10:19 UTC, merged